<?php

class KngAnchor_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_anchor';
    protected $title = 'KNG Anchor';
    protected $icon = 'eicon-anchor';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"align","label":"Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"},"justify":{"title":"Justified","icon":"eicon-text-align-justify"}},"default":"start"},{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_anchor-1.jpg"}},"prefix_class":"kng-anchor-layout-"}]},{"name":"icon_section","label":"Settings","tab":"content","controls":[{"name":"side_panel","label":"Select Side Panel","type":"select","options":{"side-mobile":"Menu Mobile Side Panel","side-menu":"Menu Desktop Side Panel","popup-menu":"Menu Desktop Popup","side-info":"Information Side Panel"},"default":"side-mobile"},{"name":"icon_type","label":"Select Icon Type","type":"select","options":{"none":"None","lib":"Library","custom":"custom"},"default":"lib"},{"name":"selected_icon","label":"Icon","type":"icons","default":{"library":"awesome","value":"fas fa-bars"},"condition":{"icon_type":"lib"}},{"name":"icon_size","label":"Icon Size(px)","type":"slider","range":{"px":{"min":15,"max":300}},"condition":{"icon_type":"lib"},"selectors":{"{{WRAPPER}} .kng-anchor-icon":"font-size: {{SIZE}}{{UNIT}};"}},{"name":"icon_margin","label":"Icon Margin(px)","type":"dimensions","control_type":"responsive","size_units":["px"],"selectors":{"{{WRAPPER}} .kng-anchor-icon":"margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"},"condition":{"icon_type!":"none"}},{"name":"title","label":"Title","type":"textarea","placeholder":"Menu"},{"name":"title_typo","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .anchor-title","condition":{"title!":""}},{"name":"icon_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .kng-anchor":"color: {{VALUE}};","{{WRAPPER}} .kng-anchor-wrap .kng-anchor-icon.custom.kng-bars span":"background-color: {{VALUE}};"}},{"name":"icon_color_hover","label":"Hover Color","type":"color","selectors":{"{{WRAPPER}} .kng-anchor:hover":"color: {{VALUE}};","{{WRAPPER}} .kng-anchor-wrap .kng-anchor-icon.custom.kng-bars:hover span":"background-color: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}