<?php

class KngQuickcontact_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_quickcontact';
    protected $title = 'KNG Quick Contact';
    protected $icon = 'eicon-mail';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_quickcontact-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_quickcontact-2.jpg"},"3":{"label":"Layout 3","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_quickcontact-3.jpg"}},"prefix_class":"kng-quick-contact-layout-"}]},{"name":"content_section","label":"Content Settings","tab":"content","controls":[{"name":"qc_image","label":"Image","type":"media","label_block":true,"condition":{"layout":"1"}},{"name":"heading_text","label":"Heading","type":"textarea","placeholder":"Enter Heading","default":"Heading Text","label_block":true},{"name":"contact_list","label":"Contact Lists","type":"repeater","controls":[{"name":"kng_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"kngi kngi-marker-alt","library":"kngi-icon"}},{"name":"item_title","label":"Item Title","type":"textarea","placeholder":"Enter item title","default":"59 Main Street, USA","label_block":true}],"default":[{"kng_icon":{"value":"kngi kngi-phone-alt1","library":"kngi-icon"},"item_title":"+012 (345) 56 998"},{"kng_icon":{"value":"kngi kngi-envelope-regular","library":"kngi-icon"},"item_title":"support@gmail.com"},{"kng_icon":{"value":"kngi kngi-marker-alt","library":"kngi-icon"},"item_title":"59 Main Street, USA"}]}]},{"name":"qc_style","label":"Style","tab":"content","controls":[{"name":"heading_text_color","label":"Heading Color","type":"color","selectors":{"{{WRAPPER}} .qc-title":"color: {{VALUE}};"}},{"name":"item_text_color","label":"Content item Color","type":"color","selectors":{"{{WRAPPER}} .qc-desc-wrap":"color: {{VALUE}};"}},{"name":"heading_typography","label":"Heading Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .qc-title"},{"name":"item_typography","label":"Item text Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .qc-desc-wrap"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}