<?php

class KngProgressbar_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_progressbar';
    protected $title = 'KNG Progress Bar';
    protected $icon = 'eicon-skill-bar';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"progressbar_list","label":"Progress Bar Lists","type":"repeater","controls":[{"name":"title","label":"Title","type":"text","placeholder":"Enter your title","default":"My Skill","label_block":true},{"name":"inner_text","label":"Inner Text","type":"text","placeholder":"e.g: Web Designer","default":"Web Designer","label_block":true},{"name":"percent","label":"Percentage","type":"slider","default":{"size":50,"unit":"%"},"label_block":true},{"name":"percent_color","label":"Percentage Color","type":"select","options":{"":"Default","primary":"Primary (#00c3ff)","second":"Secondary (#162542)","rating":"Rating (#FFB237)","body":"Body (#555555)","heading":"Heading #222222","white":"White","footer_text":"Footer Text (#aab5cc)","custom":"Custom"},"default":"","prefix_class":"","condition":[]},{"name":"custom_percent_color","label":"Custom Percentage Color","type":"color","condition":{"percent_color":"custom"},"selectors":[]}],"title_field":"{{title}} {{inner_text}}"}]},{"name":"title_style_section","label":"Title","tab":"style","controls":[{"name":"title_typo_typo","type":"typography","control_type":"group","selector":"{{WRAPPER}} .kng-heading","condition":[]},{"name":"title_typo_shadow","type":"text-shadow","control_type":"group","selector":"{{WRAPPER}} .kng-heading","condition":[]},{"name":"title_typo_color","label":"Text Color","type":"select","options":{"":"Default","primary":"Primary (#00c3ff)","second":"Secondary (#162542)","rating":"Rating (#FFB237)","body":"Body (#555555)","heading":"Heading #222222","white":"White","footer_text":"Footer Text (#aab5cc)","custom":"Custom"},"condition":[]},{"name":"title_typo_custom_color","label":"Custom Text Color","type":"color","condition":{"title_typo_color":"custom"},"selectors":{"{{WRAPPER}} .kng-heading":"color:{{VALUE}};"}}]},{"name":"percent_style","label":"Percentage","tab":"style","controls":[{"name":"percent_typo_typo","type":"typography","control_type":"group","selector":"{{WRAPPER}} .kng-progress-bar","condition":[]},{"name":"percent_typo_shadow","type":"text-shadow","control_type":"group","selector":"{{WRAPPER}} .kng-progress-bar","condition":[]},{"name":"percent_typo_color","label":"Text Color","type":"select","options":{"":"Default","primary":"Primary (#00c3ff)","second":"Secondary (#162542)","rating":"Rating (#FFB237)","body":"Body (#555555)","heading":"Heading #222222","white":"White","footer_text":"Footer Text (#aab5cc)","custom":"Custom"},"condition":[]},{"name":"percent_typo_custom_color","label":"Custom Text Color","type":"color","condition":{"percent_typo_color":"custom"},"selectors":{"{{WRAPPER}} .kng-progress-bar":"color:{{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'kng-progressbar' );
}