<?php

class KngHeading_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_heading';
    protected $title = 'KNG Heading';
    protected $icon = 'eicon-t-letter';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"icon_section","label":"Settings","tab":"content","controls":[{"name":"text_align","label":"Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"},"justify":{"title":"Justified","icon":"eicon-text-align-justify"}}}]},{"name":"title_section","label":"Title","tab":"content","controls":[{"name":"title","label":"Title","type":"textarea","label_block":true},{"name":"title_tag","label":"Heading HTML Tag","type":"select","options":{"h1":"H1","h2":"H2","h3":"H3","h4":"H4","h5":"H5","h6":"H6","div":"div","span":"span","p":"p"},"default":"h3"},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .kng-heading-wrap .item-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .kng-heading-wrap .item-title"},{"name":"heading_animate","label":"Motion Effect","type":"animation"},{"name":"heading_animation_delay","label":"Transition Delay","type":"text"}]},{"name":"sub_title_section","label":"Sub Title","tab":"content","controls":[{"name":"sub_title","label":"Sub Title","type":"textarea","label_block":true},{"name":"sub_title_color","label":"Sub Title Color","type":"color","selectors":{"{{WRAPPER}} .kng-heading-wrap .item-sub-title":"color: {{VALUE}};","{{WRAPPER}} .kng-heading-wrap .item-sub-title span:before":"background-color: {{VALUE}};","{{WRAPPER}} .kng-heading-wrap .item-sub-title span:after":"background-color: {{VALUE}};"}},{"name":"sub_title_typography","label":"Sub Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .kng-heading-wrap .item-sub-title"},{"name":"sub_title_ontop","label":"On Top","type":"switcher","default":"","label_on":"Hide","label_off":"Show","condition":{"layout":"1"}},{"name":"sub_title_space","label":"Margin(px)","type":"dimensions","allowed_dimensions":"vertical","default":{"top":"","right":"","bottom":"","left":""},"control_type":"responsive","size_units":["px"],"selectors":{"{{WRAPPER}} .kng-heading-wrap .item-sub-title":"margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}},{"name":"sub_title_style","label":"Style","type":"select","options":{"style-default":"Default","style-divider":"Divider"},"default":"style-default","condition":{"layout":"2"}},{"name":"sub_heading_animate","label":"Motion Effect","type":"animation"},{"name":"sub_heading_animation_delay","label":"Transition Delay","type":"text"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'kng-animation' );
}