<?php

class KngCustomText_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_custom_text';
    protected $title = 'KNG Custom Text';
    protected $icon = 'eicon-text';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"text_section","label":"Text","tab":"content","controls":[{"name":"text_1","label":"Text 1","type":"textarea","default":"Call Us Today"},{"name":"text_2","label":"Text 2","type":"textarea","default":"+1 (800) 456 789"}]},{"name":"style_general_section","label":"General","tab":"style","controls":[{"name":"item_space","type":"slider","label":"Bottom Spacing","control_type":"responsive","selectors":{"{{WRAPPER}} .text-item:not(:last-child)":"margin-bottom: {{SIZE}}{{UNIT}};"}}]},{"name":"text_1_section","label":"Text 1","tab":"style","controls":[{"name":"text_1_typo","type":"typography","control_type":"group","selector":"{{WRAPPER}} .text-1"},{"name":"text_1_color_color","label":"Color","type":"select","options":{"":"Default","var(--primary-color)":"Primary","var(--second-color)":"Second","var(--rating-color)":"Rating","var(--body-color)":"Body","var(--heading-color)":"Heading","var(--white-color)":"White","var(--footer_text-color)":"Footer_text","custom":"Custom"},"default":"","selectors":{"{{WRAPPER}} .text-1":"color: {{VALUE}};"},"condition":[]},{"name":"text_1_color_custom_color","label":"Custom Color","type":"color","separator":"after","condition":{"text_1_color_color":"custom"},"selectors":{"{{WRAPPER}} .text-1":"color: {{VALUE}};"}}]},{"name":"text_2_section","label":"Text 2","tab":"style","controls":[{"name":"text_2_typo","type":"typography","control_type":"group","selector":"{{WRAPPER}} .text-2"},{"name":"text_2_color_color","label":"Color","type":"select","options":{"":"Default","var(--primary-color)":"Primary","var(--second-color)":"Second","var(--rating-color)":"Rating","var(--body-color)":"Body","var(--heading-color)":"Heading","var(--white-color)":"White","var(--footer_text-color)":"Footer_text","custom":"Custom"},"default":"","selectors":{"{{WRAPPER}} .text-2":"color: {{VALUE}};"},"condition":[]},{"name":"text_2_color_custom_color","label":"Custom Color","type":"color","separator":"after","condition":{"text_2_color_color":"custom"},"selectors":{"{{WRAPPER}} .text-2":"color: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}