<?php

class KngHeaderFactor_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_header_factor';
    protected $title = 'Kng Header factor';
    protected $icon = 'eicon-cart';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_header_factor-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_header_factor-2.jpg"}}}]},{"name":"content_section","label":"Setting","tab":"content","controls":[{"name":"content_align","label":"Content Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"},"justify":{"title":"Justified","icon":"eicon-text-align-justify"}},"default":"start","condition":{"layout":"1"}},{"name":"on_search","label":"Show Search","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"inline-flex","control_type":"responsive","selectors":{"{{WRAPPER}} .kng-header-factor.layout-1 .kng-search":"display: {{VALUE}}!important;"}},{"name":"search_type","label":"Search Type","type":"select","options":{"normal":"Search Normal","product":"Search Product"},"default":"normal","condition":{"on_search":["inline-flex","none"]}},{"name":"on_cart","label":"Show Cart","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"inline-flex","control_type":"responsive","selectors":{"{{WRAPPER}} .kng-header-factor.layout-1 .kng-cart":"display: {{VALUE}}!important;"}},{"name":"on_btn_more","label":"Show Button More","type":"select","options":{"inline-flex":"Show","none":"Hide","":"Removed"},"default":"","control_type":"responsive","selectors":{"{{WRAPPER}} .kng-header-factor.layout-1 .kng-cart":"display: {{VALUE}}!important;"}},{"name":"ft_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .kng-factor":"color: {{VALUE}};"}},{"name":"ft_color_hover","label":"Hover Color","type":"color","selectors":{"{{WRAPPER}} .kng-factor:hover":"color: {{VALUE}};"}},{"name":"class","label":"Class","type":"text","separator":"after"}]},{"name":"style_section","label":"Icon","tab":"style","controls":[{"name":"icon_size","type":"slider","label":"Icon Size","range":{"px":{"min":10,"max":100}},"default":{"size":24},"control_type":"responsive","selectors":{"{{WRAPPER}} .kng-factor-item":"font-size: {{SIZE}}{{UNIT}}"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}