<?php

class KngAttorney_Widget extends Kngtheme_Core_Widget_Base{
    protected $name = 'kng_attorney';
    protected $title = 'KNG Attorney';
    protected $icon = 'eicon-icon-box';
    protected $categories = array( 'kngtheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/elements\/el-widgets\/layouts\/kng_attorney-1.jpg"}},"prefix_class":"kng-attorney-layout-"}]},{"name":"content","label":"Content","tab":"content","controls":[{"name":"selected_img","label":"Image","type":"media","default":{"url":"http:\/\/localhost\/techrona\/wp-content\/themes\/techrona\/assets\/images\/placeholder\/placeholder.png"}},{"name":"thumbnail_size","type":"image-size","label":"Image Size","control_type":"group","default":"techrona-attorney"},{"name":"attorney_name","label":"Attorney Name","type":"text","default":"Your Attorney Name"},{"name":"attorney_position","label":"Attorney Position","type":"text","default":"Family Lawyer"},{"name":"hyper_link","label":"Custom Link","type":"url","placeholder":"https:\/\/your-link.com","default":{"url":"#","is_external":"on"}},{"name":"content_padding","label":"Content Padding(px)","type":"dimensions","control_type":"responsive","size_units":["px"],"selectors":{"{{WRAPPER}} .kng-attorney-wrap .attorney-content":"padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}},{"name":"social_list","label":"Social Lists","type":"repeater","controls":[{"name":"social_name","label":"Name","type":"text","label_block":true},{"name":"social_link","label":"Link","type":"url","placeholder":"https:\/\/your-link.com","label_block":true},{"name":"social_icon","label":"Icon","type":"icons","fa4compatibility":"social","default":[]}],"default":[{"social_name":"Facebook","social_link":{"url":"https:\/\/facebook.com","is_external":"on"},"social_icon":{"value":"kngi-facebook-f","library":"kngi"}},{"social_name":"Twitter","social_link":{"url":"https:\/\/twitter.com","is_external":"on"},"social_icon":{"value":"kngi-twitter","library":"kngi"}},{"social_name":"Linkedin","social_link":{"url":"https:\/\/linkedin.com","is_external":"on"},"social_icon":{"value":"kngi-linkedin-in","library":"kngi"}},{"social_name":"Pinterest","social_link":{"url":"https:\/\/pinterest.com","is_external":"on"},"social_icon":{"value":"kngi-pinterest-p","library":"kngi"}}],"title_field":"{{{ elementor.helpers.renderIcon( this, social_icon, {}, \"i\", \"panel\" ) || \'<i class=\"{{ icon }}\" aria-hidden=\"true\"><\/i>\' }}} {{{ social_name }}}"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}